# Site settings
title: capyknock - Single Packet Authorization Port Knocking
tag_text: capyknock - Single Packet Authorization Port Knocking
description: Hide your server from bot scans
url: "https://plinioseniore.github.io" # base URL for your site ie. "https://www.example.com"
baseurl: "/capyknock" # subpath for base of site, leave blank if hosting at root

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
